black_dim = "#17261b"
black = "#1d2b20"
black_bright = "#233126"

red_dim = "#7e4747"
red = "#b86a6a"
red_bright = "#cb8d8c"

pink_dim = "#7c507a"
pink = "#b576b1"
pink_bright = "#c896c4"

green_dim = "#38663e"
green = "#54965d"
green_bright = "#7eaf83"

yellow_dim = "#6b6743"
yellow = "#9c9764"
yellow_bright = "#b3af89"

orange_dim = "#75604b"
orange = "#ab8d6f"
orange_bright = "#bfa790"

blue_dim = "#51828d"
blue = "#629ba8"
blue_bright = "#75a7b2"

purple_dim = "#634c77"
purple = "#9171ad"
purple_bright = "#aa92c1"

cyan_dim = "#4c7577"
cyan = "#71abad"
cyan_bright = "#94bfc0"

white_dim = "#81a878"
white = "#9ac78f"
white_bright = "#a6ce9c"

gray_dim = "#345034"
gray = "#455e44"
gray_bright = "#566d55"

accent_dim = "#4d8a56"
accent = "#4eb162"
accent_bright = "#98c379"

background_h = "#09110c"
background_0 = "#152419"
background_1 = "#1f2e1f"
background_2 = "#293d29"
background_3 = "#334d33"
background_4 = "#3d5c3d"
background_5 = "#476b47"

foreground_h = "#d0e5cd"
foreground_0 = "#bedbb9"
foreground_1 = "#a8cfa0"
foreground_2 = "#9ac78f"
foreground_3 = "#8bbe7e"
foreground_4 = "#78b370"
